# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  SeBL_M:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  SeBR_M:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  SeFL_M:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  SeFR_M:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ShBL_ThBL:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ShBR_ThBR:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ShFL_ThFL:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ShFR_ThFR:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ThBL_SeBL:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ThBR_SeBR:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ThFL_SeFL:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  ThFR_SeFR:
    has_velocity_limits: true
    max_velocity: 5.8178000000000001
    has_acceleration_limits: false
    max_acceleration: 0